
title: Zet draden en componenten vast met tape
hero_image: images/banner.png
description: Zet draden en componenten vast met tape
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Zet draden en componenten vast met tape
