title: Secure components using tape
hero_image: images/banner.png
description: taping-components description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
