title: Secure wires and components using tape
hero_image: images/banner.png
description: Secure wires and components using tape
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - 
    title: Secure wires and components using tape
